modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/KubeJS-Mods/Rhino/issues"
license = "MPL-2.0"

[[mods]]
modId = "rhino"
version = "${version}"
displayName = "Rhino"
authors = "LatvianModder, Mozilla"
description = '''
A fork of Mozilla's Rhino library, modified for use in mods
'''

[[dependencies.rhino]]
modId = "forge"
mandatory = true
versionRange = "[38.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rhino]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"
