modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/KubeJS-Mods/Rhino/issues"
license = "MPL-2.0"

[[mods]]
modId = "rhino"
version = "${version}"
displayName = "Rhino"
authors = "latvian.dev, Mozilla"
description = '''
A fork of Mozilla's Rhino library, modified for use in mods
'''
logoFile = "rhino_logo.png"
displayTest = "NONE"